export const IMAGE_URL_BY_NAME = {
  "1-2-Switch": "https://art.gametdb.com/switch/box/US/AACCA.png",
  "Animal Crossing: New Horizons": "https://art.gametdb.com/switch/box/US/ACBAA.png",
  "Batman: Arkham Trilogy": "https://art.gametdb.com/switch/box/US/A6DQA.png",
  "Crash Bandicoot 4: It’s About Time": "https://art.gametdb.com/switch/box/US/AXSRA.png",
  "Crash Team Racing Nitro-Fueled": "https://art.gametdb.com/switch/box/US/AST4A.png",
  "Dark Souls Remastered": "https://art.gametdb.com/switch/box/US/AK63B.png",
  "Diablo III: Eternal Collection": "https://art.gametdb.com/switch/box/US/AQ3FA.png",
  "Donkey Kong Country: Tropical Freeze": "https://art.gametdb.com/switch/box/US/AFWTA.png",
  "Donkey Kong Country Returns HD": "https://art.gametdb.com/switch/box/US/BDLWA.png",
  "DOOM Eternal": "https://art.gametdb.com/switch/box/US/A6SVA.png",
  "EA SPORTS FC 25": "https://art.gametdb.com/switch/box/US/BFY6A.png",
  "EA SPORTS FC 26": "https://art.gametdb.com/switch/box/US/A6SLA.png",
  "Everybody 1-2-Switch!": "https://art.gametdb.com/switch/box/US/ARGTA.png",
  "Game Boy – Nintendo Switch Online": "https://images.launchbox-app.com/8cbf8dfc-5c07-45e3-bbc7-8d18a661fba1.png",
  "Game Boy Advance – Nintendo Switch Online": "https://art.gametdb.com/switch/box/US/ATJWD.png",
  "Hogwarts Legacy": "https://art.gametdb.com/switch/box/US/AR3XA.png",
  "Hollow Knight": "https://art.gametdb.com/switch/box/US/AKLHA.png",
  "Hollow Knight: Silksong": "https://art.gametdb.com/switch/box/US/AUSUA.png",
  "Hyrule Warriors: Age of Calamity": "https://art.gametdb.com/switch/box/US/AXEAB.png",
  "Immortals Fenyx Rising": "https://art.gametdb.com/switch/box/US/AU84A.png",
  "It Takes Two": "https://art.gametdb.com/switch/box/US/A7GST.png",
  "LEGO DC Super-Villains": "https://art.gametdb.com/switch/box/US/ANW7A.png",
  "LEGO Harry Potter Collection": "https://art.gametdb.com/switch/box/US/AQPZA.png",
  "LEGO Horizon Adventures": "https://art.gametdb.com/switch/box/US/BFESA.png",
  "LEGO Jurassic World": "https://art.gametdb.com/switch/box/US/AUM9A.png",
  "LEGO Marvel Super Heroes": "https://art.gametdb.com/switch/box/US/AEANA.png",
  "LEGO Marvel Super Heroes 2": "https://art.gametdb.com/switch/box/US/AEANA.png",
  "LEGO NINJAGO Movie Video Game": "https://art.gametdb.com/switch/box/US/AJJ7A.png",
  "LEGO Party": "https://art.gametdb.com/switch/box/US/BPRGA.png",
  "Luigi’s Mansion 3": "https://art.gametdb.com/switch/box/US/AG3JA.png",
  "Mario & Luigi: Brothership": "https://art.gametdb.com/switch/box/US/A8E6A.png",
  "Mario Kart 8 Deluxe": "https://art.gametdb.com/switch/box/US/AABPA.png",
  "Mario Strikers: Battle League": "https://art.gametdb.com/switch/box/US/AWN6A.png",
  "Mario Tennis Aces": "https://art.gametdb.com/switch/box/US/ALERA.png",
  "Mega Man Battle Network Legacy Collection Vol. 1": "https://art.gametdb.com/switch/box/US/A6AKA.png",
  "Mega Man Battle Network Legacy Collection Vol. 2": "https://art.gametdb.com/switch/box/US/A6AKA.png",
  "Mega Man Legacy Collection": "https://art.gametdb.com/switch/box/US/AS4UA.png",
  "Mega Man Legacy Collection 2": "https://art.gametdb.com/switch/box/US/AS4UA.png",
  "Mega Man X Legacy Collection": "https://art.gametdb.com/switch/box/US/A78VA.png",
  "Mega Man X Legacy Collection 2": "https://art.gametdb.com/switch/box/US/AYRGB.png",
  "Mega Man Zero/ZX Legacy Collection": "https://art.gametdb.com/switch/box/US/AS4UA.png",
  "Metroid Dread": "https://art.gametdb.com/switch/box/US/AYL8A.png",
  "MGS Master Collection Vol. 1": "https://art.gametdb.com/switch/box/US/A7C4A.png",
  "Minecraft": "https://art.gametdb.com/switch/box/US/AEUCA.png",
  "Minecraft (Nintendo Switch Edition)": "https://art.gametdb.com/switch/box/US/AEUCA.png",
  "Minecraft Legends": "https://art.gametdb.com/switch/box/US/AZJ4A.png",
  "Minecraft Story Mode": "https://art.gametdb.com/switch/box/US/APFZA.png",
  "Monster Hunter Rise": "https://art.gametdb.com/switch/box/US/AXSEB.png",
  "Mortal Kombat 1": "https://art.gametdb.com/switch/box/US/A8WRA.png",
  "New Super Mario Bros. U Deluxe": "https://art.gametdb.com/switch/box/US/ADALA.png",
  "Ninja Gaiden 3: Razor’s Edge": "https://art.gametdb.com/switch/box/US/AT6CB.png",
  "Ninja Gaiden Sigma": "https://art.gametdb.com/switch/box/US/BBCHG.png",
  "Ninja Gaiden Sigma 2": "https://art.gametdb.com/switch/box/US/AMU5A.png",
  "Nintendo 64 – Nintendo Switch Online": "https://art.gametdb.com/switch/box/US/AZ82A.png",
  "Nintendo Entertainment System – Nintendo Switch Online": "https://art.gametdb.com/switch/box/US/ARGTA.png",
  "Nintendo Switch Sports": "https://art.gametdb.com/switch/box/US/AS8SA.png",
  "Nintendo World Championships: NES Edition": "https://art.gametdb.com/switch/box/US/A82CA.png",
  "Persona 5 Royal": "https://art.gametdb.com/switch/box/US/A42UC.png",
  "Pokkén Tournament DX": "https://art.gametdb.com/switch/box/US/BAAYA.png",
  "Pokémon Brilliant Diamond": "https://art.gametdb.com/switch/box/US/AX7QA.png",
  "Pokémon Legends: Arceus": "https://art.gametdb.com/switch/box/US/AW7KA.png",
  "Pokémon Legends: Z‑A": "https://art.gametdb.com/switch/box/US/AQRWA.png",
  "Pokémon Mystery Dungeon: Rescue Team DX": "https://art.gametdb.com/switch/box/US/AQ42A.png",
  "Pokémon Quest": "https://art.gametdb.com/switch/box/US/ARMPB.png",
  "Pokémon Scarlet": "https://art.gametdb.com/switch/box/US/ALZXA.png",
  "Pokémon Shining Pearl": "https://art.gametdb.com/switch/box/US/AX7RA.png",
  "Pokémon Shield": "https://art.gametdb.com/switch/box/US/ALZBA.png",
  "Pokémon Sword": "https://art.gametdb.com/switch/box/US/ALZAA.png",
  "Pokémon: Let’s Go, Eevee!": "https://art.gametdb.com/switch/box/US/ADW3A.png",
  "Pokémon: Let’s Go, Pikachu!": "https://art.gametdb.com/switch/box/US/ADW2A.png",
  "Pokémon Violet": "https://art.gametdb.com/switch/box/US/ALZYA.png",
  "Red Dead Redemption": "https://art.gametdb.com/switch/box/US/BAF2A.png",
  "Resident Evil 0": "https://art.gametdb.com/switch/box/US/ANW7A.png",
  "SEGA Genesis – Nintendo Switch Online": "https://art.gametdb.com/switch/box/US/APS6A.png",
  "Sifu": "https://art.gametdb.com/switch/box/US/AH3YA.png",
  "Shin Megami Tensei V": "https://art.gametdb.com/switch/box/US/AQ79A.png",
  "Ship of Harkinian (OOT native port)": "https://art.gametdb.com/switch/box/US/AUPMA.png",
  "Sonic Mania": "https://art.gametdb.com/switch/box/US/AYQ7A.png",
  "Sonic Racing Cross Worlds": "https://art.gametdb.com/switch/box/US/BMQ7A.png",
  "Splatoon 3": "https://art.gametdb.com/switch/box/US/ATTVA.png",
  "Streets of Rage 4": "https://art.gametdb.com/switch/box/US/BPEHA.png",
  "Super Bomberman R": "https://art.gametdb.com/switch/box/US/A3SYA.png",
  "Super Bomberman R2": "https://art.gametdb.com/switch/box/US/BAFSA.png",
  "Super Mario 3D All-Stars": "https://art.gametdb.com/switch/box/US/A4UJA.png",
  "Super Mario 3D World + Bowser’s Fury": "https://art.gametdb.com/switch/box/US/AXS7A.png",
  "Super Mario Bros. Wonder": "https://art.gametdb.com/switch/box/US/AH97B.png",
  "Super Mario Galaxy™ + Super Mario Galaxy™ 2": "https://art.gametdb.com/switch/box/US/ATPMB.png",
  "Super Mario Odyssey": "https://art.gametdb.com/switch/box/US/AQ3SC.png",
  "Super Mario Party Jamboree": "https://art.gametdb.com/switch/box/US/AY8KA.png",
  "Super Mario RPG": "https://art.gametdb.com/switch/box/US/A5GFA.png",
  "Super Nintendo Entertainment System – Nintendo Switch Online": "https://art.gametdb.com/switch/box/US/AXUPA.png",
  "Super Smash Bros. Ultimate": "https://art.gametdb.com/switch/box/US/AEBNC.png",
  "Teenage Mutant Ninja Turtles: Shredder’s Revenge": "https://art.gametdb.com/switch/box/US/AHWWB.png",
  "The Elder Scrolls V: Skyrim": "https://art.gametdb.com/switch/box/US/ATPCA.png",
  "The Legend of Zelda: Breath of the Wild": "https://art.gametdb.com/switch/box/US/ARVHA.png",
  "The Legend of Zelda: Echoes of Wisdom": "https://art.gametdb.com/switch/box/US/BA2TA.png",
  "The Legend of Zelda: Link’s Awakening": "https://art.gametdb.com/switch/box/US/A28NA.png",
  "The Legend of Zelda: Skyward Sword HD": "https://art.gametdb.com/switch/box/US/AZQQA.png",
  "The Legend of Zelda: Tears of the Kingdom": "https://art.gametdb.com/switch/box/US/AZTYA.png",
  "The Witcher 3: Wild Hunt – Complete Edition": "https://art.gametdb.com/switch/box/US/AK63B.png",
  "Tomb Raider I–III Remastered": "https://art.gametdb.com/switch/box/US/BAAZA.png",
  "Top Racer Collection": "https://art.gametdb.com/switch/box/US/BCFBA.png",
  "Ultra Street Fighter II: The Final Challengers": "https://art.gametdb.com/switch/box/US/AQGTA.png",
  "Xenoblade Chronicles X: Definitive Edition": "https://art.gametdb.com/switch/box/US/AUP7A.png",
  "YouTube (oficial)": "https://art.gametdb.com/switch/box/US/BBFDA.png"
};
